### ISSUE TITLE
目前存在几个bug,无法发送chat，设置无法关闭

### ISSUE THREAD

**Issue by lmuiotctf** [kirbystudy/vits-desktopPet#2]
测试系统：Windows 11

**Comment by kirbystudy** [comment]
抱歉，关于无法发送chat和设置无法关闭的问题
1. 目前版本是测试阶段，chatgpt功能接口是固定的，用户不能使用chatgpt功能，后续会设计让用户自己对接ChatGPT接口。
2. 设置无法关闭，你可以说详细一点吗。
